### ISSUE TITLE
import type in a svelte ts file throws SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by frederikhors** [PepsRyuu/nollup#189]
Using `"nollup": "0.15.6"` with https://github.com/rixo/svelte-template-hot and for the first time trying to import a `.svelte` file with `<script lang="ts">` and an `import type {...}` in it throws this error:

```
ParseError: C:\b\src\common\common.ts
SyntaxError: Unexpected token (3:12)
    import type { SvelteComponent } from "svelte";
                ^
    at compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:200:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:198:13)
    at async compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:198:13)
    at async compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:198:13)
    at async compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:198:13)
    at async compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:198:13)
    at async compileModule (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:198:13)
    at async compileInputTarget (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:231:5)
    at async Object.compile (C:\a\node_modules\nollup\lib\impl\NollupCompiler.js:302:31)
```

**Why?**

**Comment by PepsRyuu** [comment]
I'm not familiar with the Svelte plugin that much, but I assume you need to include the TypeScript Rollup plugin in your ```rollup.config.js``` file, after the Svelte plugin. Nollup is functioning correctly here.

**Comment by frederikhors** [comment]
> I'm not familiar with the Svelte plugin that much, but I assume you need to include the TypeScript Rollup plugin in your `rollup.config.js` file, after the Svelte plugin. Nollup is functioning correctly here.

Already done. I cannot share a repo right now but I can assure you everything is working correctly. Now for the first time I'm trying to import an external project (written in TS) in my own. Maybe a .tsconfig option is the problem. What a boring issue...

**Comment by frederikhors** [comment]
I think this is not Nollup's fault. Maybe this is the problem: https://github.com/rollup/plugins/issues/832.

**Comment by frederikhors** [comment]
https://github.com/rollup/plugins/issues/842
