### ISSUE TITLE
rollup-plugin-node-resolve doesn't work

### ISSUE THREAD

**Issue by vzaidman** [PepsRyuu/nollup#23]
throws:

(node:704496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined

**Comment by vzaidman** [comment]
ill open a pr shortly

**Comment by vzaidman** [comment]
damn it seems to hard for me to solve. it checks for the version of rollup it runs on for some reason

**Comment by PepsRyuu** [comment]
Hmm that's odd. I use that plugin all of the time and never came across any issues. Any particular trigger?

**Comment by vzaidman** [comment]
updated the package maybe

**Comment by vzaidman** [comment]
using it like this:
```
const replace = require('rollup-plugin-replace')
const babel = require('rollup-plugin-babel')
const node_resolve = require('rollup-plugin-node-resolve')
const commonjs = require('rollup-plugin-commonjs-alternate')

module.exports = {
  input: 'src/index.js',
  output: {
    file: 'app._hash_.js',
    format: 'esm',
    assetFileNames: '[name][extname]'
  },
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      'process.env.PORT': JSON.stringify(process.env.PORT)
    }),
    babel({
      exclude: 'node_modules/**',
      
    }),
    node_resolve(),
    commonjs({
      exclude: ['node_modules/react-redux/**']
    })
  ]
}
```

**Comment by PepsRyuu** [comment]
So I tried one of the examples and that worked. I updated the ```rollup-plugin-node-resolve``` package, and got this error:

```
Listening on http://localhost:9001
(node:18940) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollupVersion' of undefined
    at Object.options (C:\Users\paul.p.sweeney\git\github\nollup\examples\example-preact\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:219:47)
    at options.plugins.forEach.plugin (C:\Users\paul.p.sweeney\git\github\nollup\lib\impl\NollupContext.js:48:38)
    at Array.forEach (<anonymous>)
    at Object.create (C:\Users\paul.p.sweeney\git\github\nollup\lib\impl\NollupContext.js:47:25)
    at nollup (C:\Users\paul.p.sweeney\git\github\nollup\lib\index.js:481:33)
    at compiler (C:\Users\paul.p.sweeney\git\github\nollup\lib\dev-middleware.js:58:28)
    at module.exports (C:\Users\paul.p.sweeney\git\github\nollup\lib\dev-middleware.js:100:5)
    at Object.<anonymous> (C:\Users\paul.p.sweeney\git\github\nollup\lib\cli.js:93:9)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
(node:18940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Shouldn't be too hard to fix.

**Comment by vzaidman** [comment]
this fixees it:
```
module.exports = {
    create: function (options) {
        if (!options.plugins) {
            options.plugins = [];
        }

        if (!options.output) {
            options.output = {};
        }

        options.plugins.forEach(plugin => {
            plugin.meta = {rollupVersion: '2.0'};
            plugin.options && plugin.options(options);
        });

        let context = {
            input: getInputEntries(options.input),
            output: options.output,
            plugins: options.plugins,
            external: options.external || [],
            files: {},
            assets: {},
            references: {},
            module_id_generator: 0,
            bundle: {}
        };
```
but it doesnt look a very good fix :P

**Comment by PepsRyuu** [comment]
I think that fix is fine. Do you have any concerns? I looked at the Rollup documentation and "meta" only contains "rollupVersion". No need to auto-update it.

**Comment by vzaidman** [comment]
dont know, i guess it's fine

**Comment by vzaidman** [comment]
ok waiting for the newer version to be published with this small fix. thanks :)

**Comment by PepsRyuu** [comment]
Will have it released tomorrow. Feel free to submit the PR if you want the credit. :P

**Comment by vzaidman** [comment]
sure
