### ISSUE TITLE
Support array configs?

### ISSUE THREAD

**Issue by shirotech** [PepsRyuu/nollup#26]
Hi there,

I was trying this out, but it doesn't seem to support configs with arrays as I am receiving this error:

```
UnhandledPromiseRejectionWarning: Error: Input option not defined
```

Is there any particular reason we cannot support an array of configs? If not I am happy to do a PR. Thanks.

**Comment by PepsRyuu** [comment]
Hey shirotech,

Can you provide a sample config and what you would expect to occur?

**Comment by shirotech** [comment]
Hi @PepsRyuu sure, it's just a regular config but in an array format that outputs multiple bundles.

e.g.

```js
module.exports = [{
  input: {
    'app-index': 'entry/app-index.js',
    'app-results': 'entry/app-results.js',
    'cache-index': 'entry/cache-index.js',
    'cache-results': 'entry/cache-results.js',
    'styles-index': 'entry/styles-index.js',
    'styles-results': 'entry/styles-results.js',
  },
  context: 'window',
  acorn: {
    ecmaVersion: 10,
    sourceType: 'module',
  },
  output: {
    dir: 'dist/',
    format: 'system',
    sourcemap: true,
    treeshake: [Object],
    chunkFileNames: '[name].js',
  },
  plugins: [],
}, {
  input: {
    core: 'entry/core.js',
  },
  context: 'window',
  acorn: {
    ecmaVersion: 10,
    sourceType: 'module',
  },
  output: {
    dir: 'dist/',
    format: 'iife',
    sourcemap: true,
    treeshake: [Object],
    chunkFileNames: '[name].js',
  },
  plugins: [],
}, {
  input: {
    polyfills: 'entry/polyfills.js',
  },
  context: 'window',
  acorn: {
    ecmaVersion: 10,
    sourceType: 'module',
  },
  output: {
    dir: 'dist/',
    format: 'iife',
    sourcemap: true,
    treeshake: [Object],
    chunkFileNames: '[name].js',
  },
  plugins: [],
}, {
  input: {
    index: 'views/index.jsx',
  },
  context: 'window',
  acorn: {
    ecmaVersion: 10,
    sourceType: 'module',
  },
  output: {
    dir: 'dist/cjs/',
    format: 'cjs',
    sourcemap: false,
    treeshake: [Object],
    chunkFileNames: '[name].js',
    entryFileNames: '[name].html',
  },
  plugins: [],
}, {
  input: {
    results: 'views/results.jsx',
  },
  context: 'window',
  acorn: {ecmaVersion: 10, sourceType: 'module'},
  output: {
    dir: 'dist/cjs/',
    format: 'cjs',
    sourcemap: false,
    treeshake: [Object],
    chunkFileNames: '[name].js',
    entryFileNames: '[name].html',
  },
  plugins: [],
}];
```

The expected behaviour is that it can take multiple bundles + any code-splitting amongst them.

**Comment by PepsRyuu** [comment]
Thanks! I'll have a look into it as soon as I can! :)

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/tree/MultiConfig

Implemented multi-bundle support for the CLI and dev middleware, which as far as I understand is in line with the Rollup API, with support for HMR for each separate bundle. I've added "example-multi-bundle" in the examples directory.

Let me know if it works for you! 🙂

**Comment by shirotech** [comment]
Hi @PepsRyuu thanks for the prompt action!

I gave it a try, however it seems to be chucking up on postcss plugin.

At first it was complaining about commonjs, so I replaced it with the alternate version, so that's fine.

But now it's giving me this error: `TypeError: _this.addWatchFile is not a function` from postcss a quick google says that it's related to v1 of rollup or lower. https://github.com/egoist/rollup-plugin-postcss/issues/161

However upon inspecting the package.json it seems that nollup indeed supports v1 of rollup?

**Comment by PepsRyuu** [comment]
Great to hear! 

The API is designed to be compatible with the earliest v1 API, but a lot of features have been added to Rollup since the alignment. I try to cover the most commonly used API methods that works for the majority of plugins and projects.

```addWatchFile``` I'm not particularly sure what to do about. The compiler for Nollup doesn't support a watch mode, instead I have that in the dev server. I haven't particularly used the plugin before. If this function is stubbed in ```PluginContext.js``` does it work as intended? Is it watching files that are for some reason not in the current working directory?

**Comment by shirotech** [comment]
When we compile an `.scss` file, it contains imports and partials from other other files, so I think thats what the `addWatchFile` mode is all about, those files may or may not be in the dist/public directory. Any way to work around this?

**Comment by PepsRyuu** [comment]
Ah partials would make the most sense for this. If a partial is changed, because Nollup didn't import the file itself, it won't re-evaluate the root scss file and therefore the change doesn't get picked up. I have an idea on how to get this working.

Can you provide a simple sample project that replicates this issue?

**Comment by shirotech** [comment]
Very nice, it's going to take some time to strip out my current project to contain the bare minimum to test this, I will get back to you tomorrow on this. Thank you so much for looking into this.

**Comment by PepsRyuu** [comment]
No need anymore, just replicated it locally. I think I have it working.

I updated the ```MultiConfig``` branch with the ```addWatchFile``` function. Can you give it a try?

**Comment by shirotech** [comment]
Hi @PepsRyuu I gave it another shot, this time no more errors! 👍 

Here is the console log

```
Listening on http://localhost:5001
Compiled in 17849ms.
Compiled in 197ms.
Compiled in 459ms.
Compiled in 14ms.
Compiled in 3195ms.
Compiled in 190ms.
Compiled in 786ms.
Compiled in 23ms.
Compiled in 675ms.
Compiled in 6ms.
```

But then nothing appeared in my `./dist` folder, so when I opened `http://localhost:5001` nothing was there. Do you know what might have caused this? Thanks.

**Comment by shirotech** [comment]
I copied the files built from `rollup` instead, but now there are some errors

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at Array.write (**/node_modules/finalhandler/index.js:285:9)
    at listener (**/node_modules/on-finished/index.js:169:15)
    at onFinish (**/node_modules/on-finished/index.js:100:5)
    at callback (**/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (**/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by PepsRyuu** [comment]
That's normal. Nothing is supposed to appear in the ```dist``` folder, it's all compiled in memory and served from memory. If you have no index.html file in your public directory, nothing will appear either. However, you can find the compiled file at ```http://localhost:9001/[entry].js```.

Check the examples in the ```examples``` directory.

**Comment by derrickb** [comment]
Hi there,
I also have an array of configs (two) and tried installing the MultiConfig branch via:
`npm install PepsRyuu/nollup#MultiConfig -D`

When I run nollup I get this error:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollupVersion' of undefined`
Can provide the full stack if necessary!

**Comment by PepsRyuu** [comment]
Hi @derrickb,

A full stack would be appreciated. I suspect it's something to do with the ```options``` plugin API not having access to PluginContext, but need to confirm that's the issue.

**Comment by kobawan** [comment]
Hello!
I am also having the issue with array configs: https://github.com/dailymotion/vast-client-js/blob/3.0-version/rollup.config.js
I converted all the imports/exports to `require` and `module.exports = [...]` but I am getting the following error:
![Screenshot 2019-10-09 at 15 35 27](https://user-images.githubusercontent.com/9026911/66486458-e80cbe80-eaaa-11e9-9408-152c8314b952.png)

**Comment by derrickb** [comment]
```
(node:29548) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollupVersion' of undefined
    at Object.options (/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:219:47)
    at options.plugins.forEach.plugin (/node_modules/nollup/lib/impl/NollupContext.js:48:38)
    at Array.forEach (<anonymous>)
    at Object.create (/node_modules/nollup/lib/impl/NollupContext.js:47:25)
    at nollup (/node_modules/nollup/lib/index.js:479:33)
    at compiler (/node_modules/nollup/lib/dev-middleware.js:79:33)
    at module.exports (/node_modules/nollup/lib/dev-middleware.js:133:5)
    at Object.<anonymous> (/node_modules/nollup/lib/cli.js:93:9)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
(node:29548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So I just realized this is likely related to the node resolve plugin. To be honest I'm now a bit mixed up and don't know which specific issues I should be posting under.

**Comment by PepsRyuu** [comment]
@derrickb  Thanks for that, I'll have a fix published later tonight. :)

@kobawan Are you using the ```MultiConfig``` branch?

**Comment by PepsRyuu** [comment]
Rebased with master to support ESM configs.
