### ISSUE TITLE
acorn.Parser.extend is not a function

### ISSUE THREAD

**Issue by derrickb** [PepsRyuu/nollup#39]
Hello,

I've just installed nollup 0.7.6 and attempted to run it with a simple `nollup -c`

My npm output is:
```
/node_modules/nollup/lib/impl/AcornParser.js:43
let parser = acorn.Parser.extend(ImportMetaPlugin);
                          ^
TypeError: acorn.Parser.extend is not a function
    at Object.<anonymous> (/node_modules/nollup/lib/impl/AcornParser.js:43:27)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/node_modules/nollup/lib/impl/ImportExportResolver.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
```
Really looking forward to using this. Any help is much appreciated!

**Comment by PepsRyuu** [comment]
Hey @derrickb!

Thanks for reporting this issue. I noticed that I accidentally had ```acorn``` in ```devDependencies``` and not ```dependencies```. Must have accidentally swapped over when I was updating it. I've moved it back under ```dependencies```. Can you try install ```0.7.7```?

**Comment by derrickb** [comment]
`0.7.7` fixed this! Thank you
