### ISSUE TITLE
examples are failing

### ISSUE THREAD

**Issue by markope** [PepsRyuu/nollup#44]
For me none of the examples work
I cloned the repo, went into an example folder and did 
```
npm install
npm run start
```
The compile failed with an error: 
```

> @ start /Users/marko/git/nollup/examples/example-circular
> cross-env NODE_ENV=development node ../../lib/cli.js -c --content-base public --port 9001 --hot

internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/marko/git/nollup/lib/cli.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```
---
After that I tried 

```
nollup -c
```

which did compile, but the page would give an error in the browser console: 

```
Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

localhost/:1 Refused to load the image 'http://localhost:8080/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

Am I missing something?

**Comment by PepsRyuu** [comment]
Hey @markope! 

Did you run ```npm install``` in the root of the repo? The examples use Nollup relatively so you need to install those dependencies as well. 

Not sure what the latter half is about, the examples don't have custom fonts or icons.

**Comment by markope** [comment]
yes that's it. (Figured it out myself just this instance :-)

Thanks.

**Comment by PepsRyuu** [comment]
No problem! 🙂 If anything comes up feel free to write an issue!
