### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mikbry** [PepsRyuu/nollup#68]
When : I switch from a branch or pull some code and Nollup is running
```
(node:4268) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/.../RollupReactApp/.git/HEAD.lock'
    at Object.lstatSync (fs.js:939:3)
    at FSWatcher.onChange (/.../RollupReactApp/node_modules/nollup/lib/dev-middleware.js:160:20)
    at FSWatcher.emit (events.js:321:20)
    at FSWatcher.<anonymous> (/.../RollupReactApp/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/.../RollupReactApp/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/.../RollupReactApp/node_modules/chokidar/lib/fsevents-handler.js:210:14)
    at addOrChange (/.../RollupReactApp/node_modules/chokidar/lib/fsevents-handler.js:216:7)
    at /.../RollupReactApp/node_modules/chokidar/lib/fsevents-handler.js:226:39
    at /.../RollupReactApp/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:154:23)
```
Instead it should be silent or display a warning ?
Also why is it listening to .git folder ?

**Comment by PepsRyuu** [comment]
If passing custom ```watch.exclude``` rules, you need to pass directories such as ```node_modules``` and ```.git``` manually.

**Comment by mikbry** [comment]
Ok thanks
