### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ashubham** [PepsRyuu/nollup#74]
When I try to run `nollup` with the reccommended setup for `react-refresh` I get this error on one of my modules:

```
ParseError: Users/ashish/thoughtspot/node_modules/use-http/dist/index.js
TypeError: Cannot read property 'length' of undefined
    at /Users/ashish/thoughtspot/blink-v2/node_modules/nollup/lib/impl/utils.js:72:65
    at Array.forEach (<anonymous>)
    at combineSourceMapChain (/Users/ashish/thoughtspot/blink-v2/node_modules/nollup/lib/impl/utils.js:67:22)
    at Object.transform (/Users/ashish/thoughtspot/blink-v2/node_modules/nollup/lib/impl/PluginLifecycle.js:217:11)
    at async parse (/Users/ashish/thoughtspot/blink-v2/node_modules/nollup/lib/index.js:51:31)
    at async parse (/Users/ashish/thoughtspot/blink-v2/node_modules/nollup/lib/index.js:116:17)
```

The command fails and does not continue after this, just keeps printing the above error. If I comment the above import out, it fails at some other file.

**Comment by PepsRyuu** [comment]
Hey @ashubham! Thanks for reporting.

I can't seem to replicate this issue. Can you share the ```package.json``` and ```rollup.config.js``` files?

**Comment by ashubham** [comment]
rollup.config.js
```
rollupConfig.push({
    input: 'src/index.tsx',
    output: {
        dir: JS_DIR,
        entryFileNames: isProd ? '[name]-[hash].js' : '[name].js',
        format: 'es',
        sourcemap: true,
    },
    treeshake: isProd,
    plugins: [
        replace({
            'process.env.NODE_ENV': JSON.stringify(
                isProd ? 'production' : 'development',
            ),
        }),
        string({
            include: /.*\.html/,
        }),
        resolve({
            extensions,
            mainFields: ['module', 'jsnext', 'jsnext:main', 'browser', 'main'],
        }),
        json(),
        commonjs({
            include: /node_modules|ts-packages|packages/,
            sourceMap: true,
            /* named exports added resolve the following error while building react with rollup
             createElement is not exported by node_modules/react/index.js
             */
            namedExports: {
                'react': Object.keys(react),
                'react-dom': Object.keys(reactDom)
            },
        }),
        graphql(),
        patchApolloReactRequire(),
        postcss({
            plugins: [autoprefixer()],
            sourceMap: !isProd,
            extract: `${BUILD_DIR}/styles/index.css`,
            modules: {
                globalModulePaths: [
                    /.*nomodule.css/
                ]
            },
            minimize: isProd,
            use: ['sass'],
            extensions: ['.scss', '.css'],
            inject: false,
            autoModules: false,
        }),
        alias({
            entries: {
                '@utils': path.resolve(__dirname, './src/utils/'),
                '@services': path.resolve(__dirname, './src/services/')
            }
        }),
        typescript(),
        //babel(),
        isProd && terser(),
        copy({
            targets: [{ src: 'public/*', dest: BUILD_DIR }],
        }),
        !isProd &&
            serve({
                contentBase: BUILD_DIR,
                port: BLINK_PORT,
            }),
        // TODO disabling livereload due to socket hang issue with proxy server
        // !isProd &&
        //     livereload({
        //         watch: BUILD_DIR,
        //         verbose: false,
        //     }),
    ],
});
```

package.json dependencies:
```
"dependencies": {
    "@apollo/client": "beta",
    "@rollup/plugin-alias": "^3.0.1",
    "@thoughtspot/chart-lib": "*",
    "@thoughtspot/radiant": "*",
    "@thoughtspot/radiant-react": "*",
    "@thoughtspot/translations": "*",
    "@thoughtspot/logger": "*",
    "classnames": "^2.2.6",
    "core-js": "^3.6.4",
    "date-time-format-timezone": "^1.0.21",
    "detect-browser": "^4.8.0",
    "graphql": "^14.6.0",
    "i18next": "^19.1.0",
    "i18next-browser-languagedetector": "^4.0.1",
    "i18next-xhr-backend": "^3.2.2",
    "lodash": "^4.17.15",
    "mouse-presence": "^1.0.0",
    "objectFitPolyfill": "^2.3.0",
    "rangy": "^1.3.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-flexview": "^4.0.4",
    "react-i18next": "^11.3.1",
    "react-modal": "^3.11.2",
    "react-tracked": "^1.2.0",
    "regenerator-runtime": "^0.13.3",
    "rxjs": "^6.5.4",
    "url-search-params-polyfill": "^7.0.1",
    "use-http": "^0.3.8",
    "w3c-keys": "^1.0.1",
    "web-animations-js": "^2.3.2",
    "whatwg-fetch": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/schema-ast": "^1.13.1",
    "@graphql-codegen/typescript": "^1.13.1",
    "@graphql-codegen/typescript-graphql-files-modules": "^1.13.1",
    "@graphql-codegen/typescript-operations": "^1.13.1",
    "@graphql-codegen/typescript-react-apollo": "^1.13.1",
    "@kocal/rollup-plugin-graphql": "^1.0.0",
    "@rollup/plugin-commonjs": "11.0.2",
    "@rollup/plugin-json": "^4.0.3",
    "@rollup/plugin-node-resolve": "^7.1.3",
    "@rollup/plugin-replace": "^2.3.2",
    "@rollup/plugin-typescript": "^2.1.0",
    "@storybook/addon-actions": "^5.3.3",
    "@storybook/addon-links": "^5.3.3",
    "@storybook/addons": "^5.3.3",
    "@storybook/react": "^5.3.3",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@types/jest": "^25.1.0",
    "@types/lodash": "^4.14.149",
    "@types/node": "^12.12.5",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.9.4",
    "@types/react-modal": "^3.10.5",
    "@typescript-eslint/eslint-plugin": "^2.15.0",
    "@typescript-eslint/parser": "^2.15.0",
    "autoprefixer": "^9.7.3",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.0.6",
    "chalk-cli": "^4.1.0",
    "copyfiles": "^2.2.0",
    "cross-env": "^6.0.3",
    "css-loader": "^3.4.2",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.9.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-jest": "^23.6.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "fs-extra": "^8.1.0",
    "http-proxy": "^1.18.0",
    "http-proxy-rules": "^1.1.3",
    "jest": "^25.1.0",
    "jest-css-modules": "^2.1.0",
    "jest-fetch-mock": "^3.0.3",
    "jest-junit": "^10.0.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^7.0.26",
    "postcss-scss": "^2.0.0",
    "prettier": "^1.19.1",
    "purgecss": "^2.0.5",
    "replace-in-file": "^5.0.2",
    "rimraf": "^3.0.0",
    "rollup": "^2.6.1",
    "rollup-plugin-copy": "^3.1.0",
    "rollup-plugin-livereload": "^1.0.4",
    "rollup-plugin-postcss": "^2.0.3",
    "rollup-plugin-serve": "^1.0.1",
    "rollup-plugin-string": "^3.0.0",
    "rollup-plugin-terser": "^5.1.3",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.2",
    "ts-jest": "^25.1.0",
    "ts-morph": "^6.0.3",
    "ttypescript": "^1.5.10",
    "typescript": "^3.8.3",
    "typescript-transform-paths": "^1.1.14",
    "yargs": "^15.1.0"
  },
```

We are using a lerna monorepo setup, I dont know if that matters.

**Comment by PepsRyuu** [comment]
There's a bit too much going on there for me to be able to reproduce it. Are you able to isolate the plugin that's causing the error to trigger? It seems to be related to sourcemaps or a transform not returning something expected.

**Comment by houd1ni** [comment]
Same here, using these plugins:

'@rollup/plugin-commonjs'
'@rollup/plugin-typescript'
'@rollup/plugin-url'
'rollup-plugin-node-resolve'
'rollup-plugin-terser'
'rollup-plugin-replace'
'rollup-plugin-vue'
'rollup-plugin-cleaner'
'rollup-plugin-copy'
'rollup-plugin-alias'
'rollup-plugin-postcss'
'rollup-plugin-babel'

**Comment by PepsRyuu** [comment]
@houd1ni Can you provide a minimal reproducible example?

**Comment by houd1ni** [comment]
Hi, @PepsRyuu  ! I'm trying to extract the damaged plugin now. Will tell any progress.

**Comment by houd1ni** [comment]
For now it looks like, there's something with babel. Withut it jsx won't compile, but the process doesn't stuck on each file it sees.
It'  record:
```
 babel({
       extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.vue'],
       babelrc: !isDev,
       presets: isDev ? ["@vue/babel-preset-jsx"] : undefined
    }),
```
isDev is true, btw.

Digging into the utils.js now....

**Comment by houd1ni** [comment]
The   
![image](https://user-images.githubusercontent.com/7501201/87729304-ae9d7800-c7cd-11ea-822c-c464d2aab80d.png)

Prints:
```
{
code: '...code here ...',
map: {
    version: 3,
    sources: [ 'c:\\Users\\houd1ni\\Music\\my-nda-project\\src\\App.vue' ],
    names: [],
    mappings: ';AAAA;AACA;AACA,sBAAc',
    file: 'c:\\Users\\houd1ni\\Music\\my-nda-project\\src\\App.vue_1'
  },
  version: 3
}
```

**Comment by PepsRyuu** [comment]
Brilliant catch! That's a bit strange though, cause Babel works all of the time for me, wonder what caused the sourcesContent array to not exist. Just need to check for the presence of the array and fallback to the original source code I guess would be the best fix here.

PR for a working fix? :)

**Comment by houd1ni** [comment]
Researching deeper. Maybe maybe 🦜

**Comment by houd1ni** [comment]
@PepsRyuu  Looks like this should help https://github.com/PepsRyuu/nollup/pull/109  😉

**Comment by PepsRyuu** [comment]
Great! I'll give it a try in the morning. 🙂 Any insight on what Babel configuration triggers this issue?

**Comment by houd1ni** [comment]
Still nothing really interesting.
Maybe will dig a bit more after fix some other serving stuff that looks completely mine.

**Comment by PepsRyuu** [comment]
Can't reproduce it still. Tried creating a hello world Vue app with JSX using the same babel config, still no luck. Going to have to be able to at least reproduce it before merging the fix to avoid regression in the future.

**Comment by houd1ni** [comment]
@PepsRyuu Indeed. I'll make a reproduce when done with those stuff above.

**Comment by straningera** [comment]
Got the same issue and could reproduce it with this snippet on the react refresh example:

````
"dependencies": {
  "w3c-keys": "^1.0.1",
  ...
},

````

````
import { Key } from "w3c-keys";

console.log(Key);
````

**Comment by straningera** [comment]
After some investigation, I saw that the dependency is using live bindings. It is probably related to https://github.com/PepsRyuu/nollup/issues/116
